### ISSUE TITLE
libsodium not initialized

### ISSUE THREAD

**Issue by jedisct1** [facebookincubator/fizz#1]
Congrats for Fizz, this is some very exciting work!

Just glancing at the source code, it looks like there are no calls to `sodium_init()`.

This function should really be called before any other function of the library, both for performance and security (this will for example make the RNG reliable in a `chroot()` environment).

Thanks!

**Comment by knekritz** [comment]
Thanks! We've been calling this in higher layer application code but you're right the library should handle init as well. Will fix shortly.
