### ISSUE TITLE
Compilation error on Redhat

### ISSUE THREAD

**Issue by vladip1** [facebookincubator/fizz#16]
hi

Just rebuilt the latest version of folly and fail with errors building fizz:

[  3%] Building CXX object CMakeFiles/fizz.dir/crypto/Sha256.cpp.o
[  3%] Building CXX object CMakeFiles/fizz.dir/crypto/Sha384.cpp.o
[  4%] Building CXX object CMakeFiles/fizz.dir/crypto/openssl/OpenSSLKeyUtils.cpp.o
[  4%] Building CXX object CMakeFiles/fizz.dir/record/Types.cpp.o
[  5%] Building CXX object CMakeFiles/fizz.dir/record/RecordLayer.cpp.o
[  6%] Building CXX object CMakeFiles/fizz.dir/record/EncryptedRecordLayer.cpp.o
[  6%] Building CXX object CMakeFiles/fizz.dir/record/PlaintextRecordLayer.cpp.o
[  7%] Building CXX object CMakeFiles/fizz.dir/server/ServerProtocol.cpp.o
In file included from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:20:0:
/usr/local/include/folly/Overload.h: In instantiation of ‘decltype(auto) folly::variant_match(Variant&&, Cases&& ...) [with Variant = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&; Cases = {fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>}]’:
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:206:10:   required from here
/usr/local/include/folly/Overload.h:75:23: error: no matching function for call to ‘apply_visitor(folly::detail::Overload<fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)> >, boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&)’
   return apply_visitor(
          ~~~~~~~~~~~~~^
       overload(std::forward<Cases>(cases)...), std::forward<Variant>(variant));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/variant/apply_visitor.hpp:18:0,
                 from /usr/include/boost/variant/detail/hash_variant.hpp:23,
                 from /usr/include/boost/variant/variant.hpp:35,
                 from /usr/include/boost/variant.hpp:17,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/record/Types.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/crypto/signature/Signature.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/protocol/Certificate.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.h:13,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:9:
/usr/include/boost/variant/detail/apply_visitor_delayed.hpp:81:41: note: candidate: template<class Visitor> boost::apply_visitor_delayed_t<Visitor> boost::apply_visitor(Visitor&)
 inline apply_visitor_delayed_t<Visitor> apply_visitor(Visitor& visitor)
                                         ^~~~~~~~~~~~~
/usr/include/boost/variant/detail/apply_visitor_delayed.hpp:81:41: note:   template argument deduction/substitution failed:
In file included from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:20:0:
/usr/local/include/folly/Overload.h:75:23: note:   candidate expects 1 argument, 2 provided
   return apply_visitor(
          ~~~~~~~~~~~~~^
       overload(std::forward<Cases>(cases)...), std::forward<Variant>(variant));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/variant/apply_visitor.hpp:17:0,
                 from /usr/include/boost/variant/detail/hash_variant.hpp:23,
                 from /usr/include/boost/variant/variant.hpp:35,
                 from /usr/include/boost/variant.hpp:17,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/record/Types.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/crypto/signature/Signature.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/protocol/Certificate.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.h:13,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:9:
/usr/include/boost/variant/detail/apply_visitor_binary.hpp:166:1: note: candidate: template<class Visitor, class Visitable1, class Visitable2> typename Visitor::result_type boost::apply_visitor(const Visitor&, Visitable1&, Visitable2&)
 apply_visitor(
 ^~~~~~~~~~~~~
/usr/include/boost/variant/detail/apply_visitor_binary.hpp:166:1: note:   template argument deduction/substitution failed:
In file included from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:20:0:
/usr/local/include/folly/Overload.h:75:23: note:   candidate expects 3 arguments, 2 provided
   return apply_visitor(
          ~~~~~~~~~~~~~^
       overload(std::forward<Cases>(cases)...), std::forward<Variant>(variant));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/variant/apply_visitor.hpp:17:0,
                 from /usr/include/boost/variant/detail/hash_variant.hpp:23,
                 from /usr/include/boost/variant/variant.hpp:35,
                 from /usr/include/boost/variant.hpp:17,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/record/Types.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/crypto/signature/Signature.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/protocol/Certificate.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.h:13,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:9:
/usr/include/boost/variant/detail/apply_visitor_binary.hpp:141:1: note: candidate: template<class Visitor, class Visitable1, class Visitable2> typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable1&, Visitable2&)
 apply_visitor(
 ^~~~~~~~~~~~~
/usr/include/boost/variant/detail/apply_visitor_binary.hpp:141:1: note:   template argument deduction/substitution failed:
In file included from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:20:0:
/usr/local/include/folly/Overload.h:75:23: note:   candidate expects 3 arguments, 2 provided
   return apply_visitor(
          ~~~~~~~~~~~~~^
       overload(std::forward<Cases>(cases)...), std::forward<Variant>(variant));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/variant/apply_visitor.hpp:16:0,
                 from /usr/include/boost/variant/detail/hash_variant.hpp:23,
                 from /usr/include/boost/variant/variant.hpp:35,
                 from /usr/include/boost/variant.hpp:17,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/record/Types.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/crypto/signature/Signature.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/protocol/Certificate.h:11,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.h:13,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:9:
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:74:1: note: candidate: template<class Visitor, class Visitable> typename Visitor::result_type boost::apply_visitor(const Visitor&, Visitable&)
 apply_visitor(const Visitor& visitor, Visitable& visitable)
 ^~~~~~~~~~~~~
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:74:1: note:   template argument deduction/substitution failed:
/usr/include/boost/variant/detail/apply_visitor_unary.hpp: In substitution of ‘template<class Visitor, class Visitable> typename Visitor::result_type boost::apply_visitor(const Visitor&, Visitable&) [with Visitor = folly::detail::Overload<fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)> >; Visitable = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >]’:
/usr/local/include/folly/Overload.h:75:23:   required from ‘decltype(auto) folly::variant_match(Variant&&, Cases&& ...) [with Variant = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&; Cases = {fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>}]’
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:206:10:   required from here
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:74:1: error: no type named ‘result_type’ in ‘struct folly::detail::Overload<fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)> >’
/usr/local/include/folly/Overload.h: In instantiation of ‘decltype(auto) folly::variant_match(Variant&&, Cases&& ...) [with Variant = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&; Cases = {fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>}]’:
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:206:10:   required from here
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:58:1: note: candidate: template<class Visitor, class Visitable> typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable&)
 apply_visitor(Visitor& visitor, Visitable& visitable)
 ^~~~~~~~~~~~~
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:58:1: note:   template argument deduction/substitution failed:
/usr/include/boost/variant/detail/apply_visitor_unary.hpp: In substitution of ‘template<class Visitor, class Visitable> typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable&) [with Visitor = folly::detail::Overload<fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)> >; Visitable = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >]’:
/usr/local/include/folly/Overload.h:75:23:   required from ‘decltype(auto) folly::variant_match(Variant&&, Cases&& ...) [with Variant = boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&; Cases = {fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>}]’
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:206:10:   required from here
/usr/include/boost/variant/detail/apply_visitor_unary.hpp:58:1: error: no type named ‘result_type’ in ‘struct folly::detail::Overload<fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)> >’
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp: In function ‘fizz::server::AsyncActions fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)’:
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:188:32: error: could not convert ‘folly::variant_match<boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >&, {fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, 4ul, void, void, void> >&)>, fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>}>(actions, <lambda closure object>fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> >&)>{(* & state)}, <lambda closure object>fizz::server::detail::processEvent(const fizz::server::State&, fizz::Param)::<lambda(fizz::server::Actions&)>{})’ from ‘void’ to ‘fizz::server::AsyncActions {aka boost::variant<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul>, folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> > >}’
     return folly::variant_match(
            ~~~~~~~~~~~~~~~~~~~~^
         actions,
         ~~~~~~~~
         [&state](folly::Future<Actions>& futureActions) -> AsyncActions {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           return std::move(futureActions)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               .onError([&state](folly::exception_wrapper ew) {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 auto ex = ew.get_exception<FizzException>();
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 if (ex) {
                 ~~~~~~~~~
                   return detail::handleError(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       state, ReportError(std::move(ew)), ex->getAlert());
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 }
                 ~
                 return detail::handleError(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     state,
                     ~~~~~~
                     ReportError(std::move(ew)),
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     AlertDescription::unexpected_message);
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               });
               ~~~
         },
         ~~
         [](Actions& immediateActions) -> AsyncActions {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           return std::move(immediateActions);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         });
         ~~
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp: In static member function ‘static fizz::server::AsyncActions fizz::sm::EventHandler<fizz::server::ServerTypes, (fizz::server::StateEnum)1, (fizz::Event)0>::handle(const fizz::server::State&, fizz::Param)’:
/root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:1532:8: warning: ‘typename std::enable_if<((! folly::is_invocable<F>::value) && folly::is_invocable<F, T&&>::value), typename R::Return>::type folly::Future<T>::then(F&&) && [with F = fizz::sm::EventHandler<fizz::server::ServerTypes, (fizz::server::StateEnum)1, (fizz::Event)0>::handle(const fizz::server::State&, fizz::Param)::<lambda(FutureResultType)>; R = folly::futures::detail::callableResult<std::tuple<folly::Try<std::pair<fizz::PskType, folly::Optional<fizz::server::ResumptionState> > >, folly::Try<fizz::server::ReplayCacheResult> >, fizz::sm::EventHandler<fizz::server::ServerTypes, (fizz::server::StateEnum)1, (fizz::Event)0>::handle(const fizz::server::State&, fizz::Param)::<lambda(FutureResultType)> >; T = std::tuple<folly::Try<std::pair<fizz::PskType, folly::Optional<fizz::server::ResumptionState> > >, folly::Try<fizz::server::ReplayCacheResult> >; typename std::enable_if<((! folly::is_invocable<F>::value) && folly::is_invocable<F, T&&>::value), typename R::Return>::type = folly::Future<folly::small_vector<boost::variant<fizz::DeliverAppData, fizz::WriteToSocket, fizz::server::ReportHandshakeSuccess, fizz::server::ReportEarlyHandshakeSuccess, fizz::ReportError, folly::Function<void(fizz::server::State&)>, fizz::WaitForData, fizz::server::AttemptVersionFallback>, 4ul> >]’ is deprecated: use thenValue instead [-Wdeprecated-declarations]
       });
        ^
In file included from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.h:11:0,
                 from /root/vladi/http2/proxygen/proxygen/wangle/fizz/fizz/server/ServerProtocol.cpp:9:
/usr/local/include/folly/futures/Future.h:1160:3: note: declared here
   then(F&& func) && {
   ^~~~
make[2]: *** [CMakeFiles/fizz.dir/server/ServerProtocol.cpp.o] Error 1
make[1]: *** [CMakeFiles/fizz.dir/all] Error 2
make: *** [all] Error 2
[

**Comment by ngoyal** [comment]
what version of redhat/cmake/boost?

**Comment by edsburke** [comment]
Hi Fizz team,

This also happens in the v2018.10.22.00 release on Ubuntu 16.04 LTS. Would you please take a look. Thanks a lot.

```
/usr/local/include/wangle/acceptor/FizzAcceptorHandshakeHelper.h:68:28:   required from here
/usr/src/wallchain-ws/wallchain/build_dht/boost_1_57_0_GNU_5_4_0/boost/variant/detail/apply_visitor_unary.hpp:58:1: error: no type named 'result_type' in 'struct folly::detail::Overload<fizz::FizzBase<Derived, ActionMoveVisitor, StateMachine>::moveToErrorState(const folly::AsyncSocketException&) [with Derived = fizz::server::FizzServer<fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor, fizz::server::ServerStateMachine>; ActionMoveVisitor = fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor; StateMachine = fizz::server::ServerStateMachine]::<lambda(fizz::AppWrite&)>, fizz::FizzBase<Derived, ActionMoveVisitor, StateMachine>::moveToErrorState(const folly::AsyncSocketException&) [with Derived = fizz::server::FizzServer<fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor, fizz::server::ServerStateMachine>; ActionMoveVisitor = fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor; StateMachine = fizz::server::ServerStateMachine]::<lambda(fizz::EarlyAppWrite&)>, fizz::FizzBase<Derived, ActionMoveVisitor, StateMachine>::moveToErrorState(const folly::AsyncSocketException&) [with Derived = fizz::server::FizzServer<fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor, fizz::server::ServerStateMachine>; ActionMoveVisitor = fizz::server::AsyncFizzServerT<fizz::server::ServerStateMachine>::ActionMoveVisitor; StateMachine = fizz::server::ServerStateMachine]::<lambda(auto:59&)> >'
```

**Comment by edsburke** [comment]
Hi Fizz team, any updates on this? We've also faced the similar issue but on Ubutun 16 with boost 1.57. Thanks.

**Comment by ngoyal** [comment]
updating to boost 1.58 will fix this.

**Comment by edsburke** [comment]
> updating to boost 1.58 will fix this particular build error

@ngoyal thanks, it did resolve my issue.

**Comment by edsburke** [comment]
@amcrn you may want to try build folly with dynamic library, e.g.
```
cmake configure .. -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
```
, and make sure to buid folly and fizz out of the same release date.

**Comment by knekritz** [comment]
@amcrn fizz requires openssl 1.0.2 or above, you are building with 1.0.1.
