### ISSUE TITLE
Compile error in OS X

### ISSUE THREAD

**Issue by pbarbashov** [facebookincubator/fizz#28]
Mac os 10.14.4 XCode 10.2
clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

[ 58%] Building CXX object CMakeFiles/FizzTool.dir/tool/FizzServerCommand.cpp.o
/Users/pavelbarbasov/Documents/work/cpp/fizz/fizz/tool/FizzServerCommand.cpp:79:49: error: non-virtual member function
      marked 'override' hides virtual member function
      const SocketAddress& clientAddr) noexcept override;
                                                ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:160:18: note: hidden overloaded virtual function
      'folly::AsyncServerSocket::AcceptCallback::connectionAccepted' declared here: type mismatch at 1st parameter
      ('int' vs 'folly::NetworkSocket')
    virtual void connectionAccepted(
                 ^
/Users/pavelbarbasov/Documents/work/cpp/fizz/fizz/tool/FizzServerCommand.cpp:635:22: error: variable type
      'fizz::tool::(anonymous namespace)::FizzServerAcceptor' is an abstract class
  FizzServerAcceptor acceptor(port, serverContext, loop, &evb, sslContext);
                     ^
/usr/local/include/folly/io/async/AsyncServerSocket.h:160:18: note: unimplemented pure virtual method
      'connectionAccepted' in 'FizzServerAcceptor'
    virtual void connectionAccepted(
                 ^
2 errors generated.
make[2]: *** [CMakeFiles/FizzTool.dir/tool/FizzServerCommand.cpp.o] Error 1
make[1]: *** [CMakeFiles/FizzTool.dir/all] Error 2
make: *** [all] Error 2

**Comment by reanimus** [comment]
You may need to update folly to ensure it has this commit: https://github.com/facebook/folly/commit/3c6096c286de70798feefa5b2450f433476098a5

**Comment by mingtaoy** [comment]
Closing this out, please reopen if this is still an issue.
