### ISSUE TITLE
build error on archlinux

### ISSUE THREAD

**Issue by zwkno1** [facebookincubator/fizz#38]
-- The CXX compiler identification is GNU 9.1.0
-- The C compiler identification is GNU 9.1.0
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found folly: /usr
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found version "1.69.0") found components:  system thread filesystem regex context date_time program_options chrono atomic 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1c")  
-- Found glog: /usr/lib/libglog.so  
-- Found double_conversion: /usr/lib/libdouble-conversion.so  
-- Found librt: /usr/lib/librt.so  
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Found Sodium: /usr/lib/libsodium.so  
-- Found gflags from package config
-- Found libevent: /usr/lib/libevent.so  
-- Found LIBGMOCK: /usr/lib/libgmock_main.so  
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "//include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "//include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by zwkno1** [comment]
source code:

https://github.com/facebookincubator/fizz/archive/v/2019.08.05.00.tar.gz

**Comment by MrAnno** [comment]
Hello,

Are you using [AUR](https://aur.archlinux.org/packages/fizz/)?
If so, your problem might be packaging issue, I wouldn't bother the upstream maintainers in this case. Please post a comment in AUR before opening an issue here.

I build the AUR package regularly in a [clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) without issues. Could you share your CMake logs (`CMakeCache`, `CMakeOutput`, `CMakeError`)?

**Comment by zwkno1** [comment]
it's folly's cmake targets error.
