### ISSUE TITLE
libz link error while building fizz 

### ISSUE THREAD

**Issue by spothineni** [facebookincubator/fizz#40]
[  0%] Building CXX object CMakeFiles/fizz.dir/record/EncryptedRecordLayer.cpp.o
[  1%] Building CXX object CMakeFiles/fizz.dir/record/PlaintextRecordLayer.cpp.o
[  1%] Building CXX object CMakeFiles/fizz.dir/server/ServerProtocol.cpp.o
[  2%] Building CXX object CMakeFiles/fizz.dir/server/CertManager.cpp.o
[  2%] Building CXX object CMakeFiles/fizz.dir/server/State.cpp.o
[  3%] Building CXX object CMakeFiles/fizz.dir/server/FizzServer.cpp.o
[  3%] Building CXX object CMakeFiles/fizz.dir/server/TicketCodec.cpp.o
[  4%] Building CXX object CMakeFiles/fizz.dir/server/CookieCipher.cpp.o
[  4%] Building CXX object CMakeFiles/fizz.dir/server/ReplayCache.cpp.o
[  5%] Building CXX object CMakeFiles/fizz.dir/server/SlidingBloomReplayCache.cpp.o
[  5%] Building CXX object CMakeFiles/fizz.dir/protocol/AsyncFizzBase.cpp.o
[  6%] Building CXX object CMakeFiles/fizz.dir/protocol/Types.cpp.o
[  6%] Building CXX object CMakeFiles/fizz.dir/protocol/Exporter.cpp.o
[  7%] Building CXX object CMakeFiles/fizz.dir/protocol/DefaultCertificateVerifier.cpp.o
[  7%] Building CXX object CMakeFiles/fizz.dir/protocol/Events.cpp.o
[  8%] Building CXX object CMakeFiles/fizz.dir/protocol/KeyScheduler.cpp.o
[  8%] Building CXX object CMakeFiles/fizz.dir/protocol/Certificate.cpp.o
[  9%] Building CXX object CMakeFiles/fizz.dir/protocol/CertDecompressionManager.cpp.o
[  9%] Building CXX object CMakeFiles/fizz.dir/protocol/ZlibCertificateCompressor.cpp.o
[ 10%] Building CXX object CMakeFiles/fizz.dir/protocol/ZlibCertificateDecompressor.cpp.o
[ 10%] Building CXX object CMakeFiles/fizz.dir/protocol/clock/SystemClock.cpp.o
[ 11%] Building CXX object CMakeFiles/fizz.dir/extensions/exportedauth/ExportedAuthenticator.cpp.o
[ 11%] Building CXX object CMakeFiles/fizz.dir/extensions/tokenbinding/Types.cpp.o
[ 12%] Building CXX object CMakeFiles/fizz.dir/extensions/tokenbinding/TokenBindingConstructor.cpp.o
[ 12%] Building CXX object CMakeFiles/fizz.dir/extensions/tokenbinding/TokenBindingClientExtension.cpp.o
[ 13%] Building CXX object CMakeFiles/fizz.dir/extensions/tokenbinding/Validator.cpp.o
[ 13%] Building CXX object CMakeFiles/fizz.dir/client/State.cpp.o
[ 14%] Building CXX object CMakeFiles/fizz.dir/client/ClientProtocol.cpp.o
[ 14%] Building CXX object CMakeFiles/fizz.dir/client/SynchronizedLruPskCache.cpp.o
[ 15%] Building CXX object CMakeFiles/fizz.dir/client/EarlyDataRejectionPolicy.cpp.o
[ 15%] Building CXX object CMakeFiles/fizz.dir/util/FizzUtil.cpp.o
[ 16%] Linking CXX static library lib/libfizz.a
[ 21%] Built target fizz
Scanning dependencies of target BogoShim
[ 22%] Building CXX object CMakeFiles/BogoShim.dir/test/BogoShim.cpp.o
[ 22%] Linking CXX executable bin/BogoShim
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /home/spothineni/Sudhir/hbase-native-client/thirdparty/folly/usr/local/lib/libfolly.a(Zlib.cpp.o): undefined reference to symbol 'inflateInit2_'
//lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/BogoShim.dir/build.make:102: bin/BogoShim] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/BogoShim.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Its getting series of linker errors start with libz, gflags, lz4, what si the correct way of building folly and link it to fizz?

**Comment by zInPython** [comment]
I`ve got the same problem . Is there any solution？Could anyone help me ？
