### ISSUE TITLE
How to use delegated credential in fizz s_server ...?

### ISSUE THREAD

**Issue by william-zk** [facebookincubator/fizz#51]
I'd like to try the feature of DelegatedCredential, but I didn't find any doc or manual in ` fizz s_sever -help`, so how can I use it in `fizz s_client` and `fizz s_server`?

**Comment by reanimus** [comment]
At the moment, only the client-side support has landed. Server-side support is in the process of review and should be landed soon as well. If you look at the client, it has some setup for the client, if you'd like to take a look: https://github.com/facebookincubator/fizz/blob/master/fizz/tool/FizzClientCommand.cpp#L555-L561

You can try it with the client by using the `-delegatedcred` flag.

**Comment by william-zk** [comment]
Thanks a lot :-)
