### ISSUE TITLE
Code of conduct contains a broken link.

### ISSUE THREAD

**Issue by korniltsev** [facebookincubator/fizz#6]
This file [CODE_OF_CONDUCT.md](https://github.com/facebookincubator/fizz/blob/master/CODE_OF_CONDUCT.md)
contains a broken (404) link to [https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct)

**Comment by knekritz** [comment]
Thanks for reporting, this is fixed in #5
