### ISSUE TITLE
The release artifacts are the same in the last two releases

### ISSUE THREAD

**Issue by chenrui333** [facebookincubator/fizz#63]
It looks like the release artifacts are the same in terms of md5 hash

```
d95050d02586e30c71f3a517cca619a6e415932b438ff20a62ee3192a389276a  fizz-v2021.06.14.00.tar.gz
d95050d02586e30c71f3a517cca619a6e415932b438ff20a62ee3192a389276a  fizz-v2021.06.21.00.tar.gz
```

**Comment by mingtaoy** [comment]
These releases are automatically generated weekly. If there are no changes, then the releases will be the same. Fizz doesn't (currently) have a concept of stable versioning.
