### ISSUE TITLE
zstd is not added to cmake or fbcode builder manifests

### ISSUE THREAD

**Issue by fredemmott** [facebookincubator/fizz#65]
Repro:

```
os_image=ubuntu:18.04 gcc_version=7 make_parallelism=5 travis_cache_dir=~/travis_ccache \
  build/fbcode_builder/travis_docker_build.sh
```

The dockerized build fails for a few reasons:

1. the dependency is not declared in the manifests, so the header files are unavailable
2. zstd was never added to fizz's cmake, so building the shared object fails

On github actions, (1) is not an issue because of a different dependency installation order/process, and (2) is not an issue because zstd is built a static library, so undefined symbol errors are delayed.

While Travis isn't supported any more, being able to build a docker image is still useful, and fizz should handle zstd in CMake regardless.

**Comment by mingtaoy** [comment]
This was fixed in 32ad80d0ceb9b2bd3771afd1a688ffdd99ef5fff and 38cefa8c5b3fe2267c570db7312272a2e29756ec
