### ISSUE TITLE
passing optional as this discards qualifiers

### ISSUE THREAD

**Issue by fxbrain** [facebookincubator/fizz#7]
fizz/fizz/protocol/test/ProtocolTest.h:135:5 passing ‘const folly::Optional<bool>’ as ‘this’ argument discards qualifiers.

EXPECT_CALL(*ret, setSkipFailedDecryption(*skipFailedDecryption)); 

may be defined as:

EXPECT_CALL(*ret, setSkipFailedDecryption(skipFailedDecryption.value())); 

to successfully compile the tests, since setSkipFailedDecryption in EncryptedRecordLayer.h expects bool.

**Comment by mingtaoy** [comment]
@fxbrain , what compiler were you using?

**Comment by knekritz** [comment]
I made this change in 3032b10. Let me know if anything else is required (this issue does not repro in any of the platforms we are compiling on).
