### ISSUE TITLE
ClientHello Callback

### ISSUE THREAD

**Issue by SteveSelva** [facebookincubator/fizz#90]
Does Fizz has callback function at the ClientHello message in TLS handshake?

**Comment by SteveSelva** [comment]
I want to generate a SSL Certificate on the fly using the SNI extension from the `ClientHello` message. Is this approach possible with the `CertManager` and if so how to do? Can you provide a example code please.

**Comment by knekritz** [comment]
Yes, it's certainly possible to generate a new cert on the fly in the CertManager (with a custom implementation of getCert()).

**Comment by SteveSelva** [comment]
Thanks @knekritz for your assistance.
